# Generated by Django 3.0.5 on 2020-04-18 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_TEST', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste', models.BigIntegerField(default=0, verbose_name='Вычет: ')),
                ('waste_desc', models.CharField(max_length=255, verbose_name='На что тебе этот рубль? ')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='all_time_balance',
            field=models.BigIntegerField(default=0, verbose_name='Баланс за всё время: '),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='Заработано денег: '),
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
        migrations.AddField(
            model_name='expenses',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
