# Generated by Django 3.0.5 on 2020-04-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_TEST', '0003_auto_20200418_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='waste_desc',
            field=models.TextField(max_length=255, verbose_name='На что тебе этот рубль? '),
        ),
    ]
