# Generated by Django 3.0.5 on 2020-04-18 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_TEST', '0004_auto_20200418_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='all_time_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Заработано денег: ')),
                ('all_time_balance', models.BigIntegerField(default=0, verbose_name='Баланс за всё время: ')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
