# Generated by Django 3.0.5 on 2020-04-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST_TEST', '0005_auto_20200418_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='all_time_balance',
            field=models.BigIntegerField(default=0, verbose_name='Баланс за всё время: '),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='Заработано денег: '),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
